name: Release Note to Notion

on:
  pull_request:
    types: [closed]
    # トリガーとなるマージ先のブランチ
    branches:
      - main

jobs:
  create-release-note:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Register PR detail
        env:
          LABELS_JSON: '${{ toJSON(github.event.pull_request.labels) }}'
        run: |
          echo "REPOSITORY_NAME=${{ github.event.repository.name }}" >> $GITHUB_ENV
          echo "PR_URL=${{ github.event.pull_request.html_url }}" >> $GITHUB_ENV
          echo "PR_TITLE=${{ github.event.pull_request.title }}" >> $GITHUB_ENV
          echo "PR_BODY=$(echo '${{ github.event.pull_request.body }}' | base64)" >> $GITHUB_ENV
          echo "Debug: Raw labels from GitHub:"
          echo '${{ toJSON(github.event.pull_request.labels) }}'
          echo "Debug: Labels from env variable:"
          echo "$LABELS_JSON"
          echo "PR_LABELS='$LABELS_JSON'" >> $GITHUB_ENV

      - name: Install dependencies
        run: bun install

      - name: Generate release note
        run: bun run release-note
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
